-- AlterTable
ALTER TABLE "Vendor" ADD COLUMN     "isBussinessIdVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isNidVerify" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "website" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "vendorCode" SET DEFAULT 'VEN-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 8));
